f = open("text.txt", "r")
read_content = f.read()
print(read_content)
f = open("json.json", "r")
read_content = f.read()
print(read_content)
f = open("csv.csv", "r")
read_content = f.read()
print(read_content)