f = open("files/text.txt", "r")
read_content = f.read()
print(read_content)
f = open("files/json.json", "r")
read_content = f.read()
print(read_content)
f = open("files/csv.csv", "r")
read_content = f.read()
print(read_content)